CREATE TABLE IF NOT EXISTS campus_settlement_reconcile_difference_record (
    id BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '结算对账差异记录ID',
    payout_batch_no VARCHAR(100) NOT NULL COMMENT '打款批次号',
    settlement_record_id BIGINT NOT NULL COMMENT '结算记录ID',
    relay_order_id VARCHAR(32) NOT NULL COMMENT '代送订单号',
    courier_profile_id BIGINT NOT NULL COMMENT '配送员资料ID',
    difference_type VARCHAR(40) NOT NULL COMMENT '差异类型',
    expected_amount DECIMAL(10,2) COMMENT '预期金额',
    actual_amount DECIMAL(10,2) COMMENT '实际金额',
    difference_remark VARCHAR(255) NOT NULL COMMENT '差异说明',
    process_status VARCHAR(20) NOT NULL DEFAULT 'OPEN' COMMENT '处理状态(OPEN/RESOLVED)',
    process_result VARCHAR(30) COMMENT '处理结果(CONFIRMED/MARKED_INVALID/FOLLOWED_UP)',
    process_remark VARCHAR(255) COMMENT '处理备注',
    reported_by_employee_id BIGINT NOT NULL COMMENT '记录管理员ID',
    reported_at DATETIME NOT NULL COMMENT '记录时间',
    processed_by_employee_id BIGINT COMMENT '处理管理员ID',
    processed_at DATETIME COMMENT '处理时间',
    source VARCHAR(30) NOT NULL DEFAULT 'MANUAL_ADMIN' COMMENT '来源(MANUAL_ADMIN/SIMULATED_RECONCILE)',
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    INDEX idx_campus_settlement_reconcile_diff_batch_no (payout_batch_no),
    INDEX idx_campus_settlement_reconcile_diff_settlement (settlement_record_id),
    INDEX idx_campus_settlement_reconcile_diff_order (relay_order_id),
    INDEX idx_campus_settlement_reconcile_diff_type (difference_type),
    INDEX idx_campus_settlement_reconcile_diff_status (process_status),
    INDEX idx_campus_settlement_reconcile_diff_reported_at (reported_at),
    CONSTRAINT fk_campus_settlement_reconcile_diff_settlement FOREIGN KEY (settlement_record_id) REFERENCES campus_settlement_record(id),
    CONSTRAINT fk_campus_settlement_reconcile_diff_order FOREIGN KEY (relay_order_id) REFERENCES campus_relay_order(id),
    CONSTRAINT fk_campus_settlement_reconcile_diff_courier FOREIGN KEY (courier_profile_id) REFERENCES campus_courier_profile(id),
    CONSTRAINT fk_campus_settlement_reconcile_diff_reported_employee FOREIGN KEY (reported_by_employee_id) REFERENCES employee(id),
    CONSTRAINT fk_campus_settlement_reconcile_diff_processed_employee FOREIGN KEY (processed_by_employee_id) REFERENCES employee(id)
) COMMENT='校园代送结算对账差异记录表';
