package com.cangqiong.takeaway.campus.enums;

public enum CampusRelayOrderStatus {
    PENDING_PAYMENT,
    BUILDING_PRIORITY_PENDING,
    WAITING_ACCEPT,
    ACCEPTED,
    PICKED_UP,
    DELIVERING,
    AWAITING_CONFIRMATION,
    COMPLETED,
    AFTER_SALE_OPEN,
    AFTER_SALE_RESOLVED,
    AFTER_SALE_REJECTED,
    CANCELLED
}
