CREATE TABLE IF NOT EXISTS employee (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL,
    phone VARCHAR(20) NOT NULL UNIQUE,
    password VARCHAR(100) NOT NULL,
    position VARCHAR(50) NOT NULL,
    department VARCHAR(50) NOT NULL,
    entry_date DATE NOT NULL,
    status TINYINT DEFAULT 1,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS category (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL UNIQUE,
    sort INT DEFAULT 0,
    status TINYINT DEFAULT 1,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS dish (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL UNIQUE,
    category_id BIGINT NOT NULL,
    price DECIMAL(10, 2) NOT NULL,
    description VARCHAR(255),
    image VARCHAR(255),
    status TINYINT DEFAULT 1,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_dish_category FOREIGN KEY (category_id) REFERENCES category(id)
);

CREATE TABLE IF NOT EXISTS setmeal (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL UNIQUE,
    category_id BIGINT NOT NULL,
    price DECIMAL(10, 2) NOT NULL,
    description VARCHAR(255),
    image VARCHAR(255),
    status TINYINT DEFAULT 1,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_setmeal_category FOREIGN KEY (category_id) REFERENCES category(id)
);

CREATE TABLE IF NOT EXISTS setmeal_dish (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    setmeal_id BIGINT NOT NULL,
    dish_id BIGINT NOT NULL,
    quantity INT DEFAULT 1,
    CONSTRAINT fk_setmeal_dish_setmeal FOREIGN KEY (setmeal_id) REFERENCES setmeal(id),
    CONSTRAINT fk_setmeal_dish_dish FOREIGN KEY (dish_id) REFERENCES dish(id)
);

CREATE TABLE IF NOT EXISTS user (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL,
    phone VARCHAR(20) NOT NULL UNIQUE,
    password VARCHAR(100) NOT NULL,
    avatar VARCHAR(255),
    status TINYINT DEFAULT 1,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS cart (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    dish_id BIGINT,
    setmeal_id BIGINT,
    quantity INT NOT NULL DEFAULT 1,
    checked TINYINT DEFAULT 1,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_cart_user FOREIGN KEY (user_id) REFERENCES user(id),
    CONSTRAINT fk_cart_dish FOREIGN KEY (dish_id) REFERENCES dish(id),
    CONSTRAINT fk_cart_setmeal FOREIGN KEY (setmeal_id) REFERENCES setmeal(id)
);

CREATE TABLE IF NOT EXISTS address (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    consignee VARCHAR(50) NOT NULL,
    phone VARCHAR(20) NOT NULL,
    province VARCHAR(50) NOT NULL,
    city VARCHAR(50) NOT NULL,
    district VARCHAR(50) NOT NULL,
    detail VARCHAR(255) NOT NULL,
    is_default TINYINT DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_address_user FOREIGN KEY (user_id) REFERENCES user(id)
);

CREATE TABLE IF NOT EXISTS orders (
    id VARCHAR(32) PRIMARY KEY,
    user_id BIGINT NOT NULL,
    customer_name VARCHAR(50) NOT NULL,
    customer_phone VARCHAR(20) NOT NULL,
    customer_address VARCHAR(255) NOT NULL,
    total_amount DECIMAL(10, 2) NOT NULL,
    status TINYINT DEFAULT 0,
    payment_time TIMESTAMP,
    delivery_time TIMESTAMP,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_orders_user FOREIGN KEY (user_id) REFERENCES user(id)
);

CREATE TABLE IF NOT EXISTS order_item (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id VARCHAR(32) NOT NULL,
    dish_id BIGINT,
    setmeal_id BIGINT,
    name VARCHAR(100) NOT NULL,
    price DECIMAL(10, 2) NOT NULL,
    quantity INT NOT NULL,
    total DECIMAL(10, 2) NOT NULL,
    CONSTRAINT fk_order_item_order FOREIGN KEY (order_id) REFERENCES orders(id),
    CONSTRAINT fk_order_item_dish FOREIGN KEY (dish_id) REFERENCES dish(id),
    CONSTRAINT fk_order_item_setmeal FOREIGN KEY (setmeal_id) REFERENCES setmeal(id)
);

CREATE TABLE IF NOT EXISTS shop_config (
    id BIGINT PRIMARY KEY,
    is_open TINYINT DEFAULT 1,
    rest_notice VARCHAR(255) DEFAULT '',
    last_updated TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS shop_business_hour (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    day_key VARCHAR(20) NOT NULL UNIQUE,
    day_name VARCHAR(20) NOT NULL,
    is_open TINYINT DEFAULT 1,
    open_time VARCHAR(5) NOT NULL,
    close_time VARCHAR(5) NOT NULL,
    sort INT DEFAULT 0
);

CREATE TABLE IF NOT EXISTS campus_customer_profile (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL UNIQUE,
    real_name VARCHAR(50) NOT NULL,
    identity_type VARCHAR(20) NOT NULL,
    identity_no VARCHAR(50) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_campus_customer_profile_user FOREIGN KEY (user_id) REFERENCES user(id)
);

CREATE TABLE IF NOT EXISTS campus_courier_profile (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL UNIQUE,
    real_name VARCHAR(50) NOT NULL,
    gender VARCHAR(20),
    campus_zone VARCHAR(50),
    student_no VARCHAR(50) NOT NULL,
    college VARCHAR(100),
    major VARCHAR(100),
    class_name VARCHAR(100),
    dormitory_building VARCHAR(50) NOT NULL,
    dormitory_room VARCHAR(50),
    enabled_work_in_own_building TINYINT DEFAULT 1,
    applicant_remark VARCHAR(255),
    id_card_last4 VARCHAR(4),
    emergency_contact_name VARCHAR(50) NOT NULL,
    emergency_contact_phone VARCHAR(20) NOT NULL,
    verification_photo_url VARCHAR(255),
    schedule_attachment_url VARCHAR(255),
    review_status VARCHAR(20) NOT NULL,
    review_comment VARCHAR(255),
    reviewed_by_employee_id BIGINT,
    reviewed_at TIMESTAMP,
    enabled TINYINT DEFAULT 1,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_campus_courier_profile_user FOREIGN KEY (user_id) REFERENCES user(id),
    CONSTRAINT fk_campus_courier_profile_employee FOREIGN KEY (reviewed_by_employee_id) REFERENCES employee(id)
);

CREATE TABLE IF NOT EXISTS campus_pickup_point (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(50) NOT NULL UNIQUE,
    name VARCHAR(100) NOT NULL,
    gate_area VARCHAR(100) NOT NULL,
    description VARCHAR(255) NOT NULL,
    enabled TINYINT DEFAULT 1,
    sort INT DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS campus_relay_order (
    id VARCHAR(32) PRIMARY KEY,
    customer_user_id BIGINT NOT NULL,
    courier_profile_id BIGINT,
    pickup_point_id BIGINT NOT NULL,
    delivery_target_type VARCHAR(30) NOT NULL,
    delivery_building VARCHAR(100) NOT NULL,
    delivery_detail VARCHAR(255) NOT NULL,
    delivery_contact_name VARCHAR(50) NOT NULL,
    delivery_contact_phone VARCHAR(20) NOT NULL,
    food_description VARCHAR(255) NOT NULL,
    external_platform_name VARCHAR(50),
    external_order_ref VARCHAR(100),
    pickup_code VARCHAR(50),
    base_fee DECIMAL(10, 2) NOT NULL,
    priority_fee DECIMAL(10, 2) NOT NULL DEFAULT 0,
    tip_fee DECIMAL(10, 2) NOT NULL DEFAULT 0,
    total_amount DECIMAL(10, 2) NOT NULL,
    payment_status VARCHAR(20) NOT NULL,
    order_status VARCHAR(30) NOT NULL,
    priority_dormitory_building VARCHAR(50),
    paid_at TIMESTAMP,
    priority_window_deadline TIMESTAMP,
    accepted_at TIMESTAMP,
    cancel_locked_until TIMESTAMP,
    picked_up_at TIMESTAMP,
    delivered_at TIMESTAMP,
    auto_complete_at TIMESTAMP,
    cancelled_at TIMESTAMP,
    after_sale_applied_at TIMESTAMP,
    after_sale_handled_at TIMESTAMP,
    pickup_proof_image_url VARCHAR(255),
    cancel_reason VARCHAR(255),
    customer_remark VARCHAR(255),
    courier_remark VARCHAR(255),
    after_sale_reason VARCHAR(255),
    after_sale_handle_action VARCHAR(20),
    after_sale_handle_remark VARCHAR(255),
    after_sale_handled_by_employee_id BIGINT,
    after_sale_decision_type VARCHAR(20),
    after_sale_decision_amount DECIMAL(10, 2),
    after_sale_decision_remark VARCHAR(255),
    after_sale_decided_by_employee_id BIGINT,
    after_sale_decided_at TIMESTAMP,
    after_sale_execution_status VARCHAR(20),
    after_sale_execution_remark VARCHAR(255),
    after_sale_execution_reference_no VARCHAR(100),
    after_sale_executed_by_employee_id BIGINT,
    after_sale_executed_at TIMESTAMP,
    after_sale_execution_corrected TINYINT DEFAULT 0 NOT NULL,
    after_sale_execution_corrected_by_employee_id BIGINT,
    after_sale_execution_corrected_at TIMESTAMP,
    exception_type VARCHAR(50),
    exception_remark VARCHAR(255),
    exception_reported_at TIMESTAMP,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_campus_relay_order_user FOREIGN KEY (customer_user_id) REFERENCES user(id),
    CONSTRAINT fk_campus_relay_order_courier FOREIGN KEY (courier_profile_id) REFERENCES campus_courier_profile(id),
    CONSTRAINT fk_campus_relay_order_pickup_point FOREIGN KEY (pickup_point_id) REFERENCES campus_pickup_point(id),
    CONSTRAINT fk_campus_relay_order_after_sale_employee FOREIGN KEY (after_sale_handled_by_employee_id) REFERENCES employee(id),
    CONSTRAINT fk_campus_relay_order_after_sale_decision_employee FOREIGN KEY (after_sale_decided_by_employee_id) REFERENCES employee(id),
    CONSTRAINT fk_campus_relay_order_after_sale_execution_employee FOREIGN KEY (after_sale_executed_by_employee_id) REFERENCES employee(id),
    CONSTRAINT fk_campus_relay_order_after_sale_execution_corrected_employee FOREIGN KEY (after_sale_execution_corrected_by_employee_id) REFERENCES employee(id)
);

CREATE TABLE IF NOT EXISTS campus_location_report (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    relay_order_id VARCHAR(32) NOT NULL,
    courier_profile_id BIGINT NOT NULL,
    latitude DECIMAL(10, 7) NOT NULL,
    longitude DECIMAL(10, 7) NOT NULL,
    source VARCHAR(30) NOT NULL,
    note VARCHAR(255),
    reported_at TIMESTAMP NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_campus_location_report_order FOREIGN KEY (relay_order_id) REFERENCES campus_relay_order(id),
    CONSTRAINT fk_campus_location_report_courier FOREIGN KEY (courier_profile_id) REFERENCES campus_courier_profile(id)
);

CREATE TABLE IF NOT EXISTS campus_settlement_record (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    relay_order_id VARCHAR(32) NOT NULL UNIQUE,
    courier_profile_id BIGINT NOT NULL,
    gross_amount DECIMAL(10, 2) NOT NULL,
    platform_commission DECIMAL(10, 2) NOT NULL DEFAULT 0,
    pending_amount DECIMAL(10, 2) NOT NULL,
    settlement_status VARCHAR(20) NOT NULL,
    payout_status VARCHAR(20),
    payout_batch_no VARCHAR(100),
    payout_remark VARCHAR(255),
    payout_reference_no VARCHAR(100),
    payout_recorded_by_employee_id BIGINT,
    payout_recorded_at TIMESTAMP,
    payout_verified TINYINT DEFAULT 0 NOT NULL,
    payout_verified_by_employee_id BIGINT,
    payout_verified_at TIMESTAMP,
    payout_verify_remark VARCHAR(255),
    settled_at TIMESTAMP,
    remark VARCHAR(255),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_campus_settlement_record_order FOREIGN KEY (relay_order_id) REFERENCES campus_relay_order(id),
    CONSTRAINT fk_campus_settlement_record_courier FOREIGN KEY (courier_profile_id) REFERENCES campus_courier_profile(id),
    CONSTRAINT fk_campus_settlement_record_payout_employee FOREIGN KEY (payout_recorded_by_employee_id) REFERENCES employee(id),
    CONSTRAINT fk_campus_settlement_record_payout_verify_employee FOREIGN KEY (payout_verified_by_employee_id) REFERENCES employee(id)
);
